language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

notifications:
  email:
    - recipients:
        - andrew.e.kimberly@gmail.com

install:
  - npm install
  - npm install -g travis-ci-cloudfront-invalidation
  - npm run build -- --prod

script:
  - npm run lint

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_S3_BUCKET
  skip_cleanup: true
  region: $AWS_REGION
  local_dir: www
  on:
    tags: true

after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY -s $AWS_SECRET_ACCESS_KEY -c $AWS_CF_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST -o $TRAVIS_BRANCH
